version: '3.5'

services:
  db:
    container_name: mf-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=memefactory
    ports:
      - '5432:5432'

  be:
    container_name: mf-be
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
     - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=1
      - DATABASE_DATABASE=memefactory
      - DATABASE_LOGGING=true
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
